[package]
name = "craft"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
log = "0.4.0"
env_logger = "0.9.0"
inkwell = { version = "0.1.0", features = ["llvm14-0"]}

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.1"
